name: Linting
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install linter
        run: python -m pip install flake8
      - name: Linting
        run: |
          cd python-project-83
          flake8 --ignore=F401 page_analyzer/app.py
        
          
      