name: linter-check
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install flake8
        run: python -m pip install flake8
      - name: Linting
        run: flake8 --ignore=F401 page_analyzer/app.py
      - name: Deploy on the Render
        env:
            deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: curl ${{ deploy_url }}

